### ISSUE TITLE
Suggested changes to documentation

### ISSUE THREAD

**Issue by JunHerng** [s-fifteen-instruments/guardian#9]
##### Installation

- Vault init phase 2 -> Vault is unsealed. Should mention briefly that vault is brought down in between init phase 1 and 2

- Watcher -> Unclear sentence. "When a file notification is ready, spawn a thread to read the epoch file and send to the local Vault instance Key Value version 2 secrets engine QKEYs endpoint"

### User
- Certificates -> QKD Controller is first mentioned here before the actual section. Maybe link to the section here or provide one sentence summary of Controller

**Comment by syed82ab** [comment]
Noted.

In init phase, Vault server is running all the way to the end. vault_inits just run calls to vault via python hvac
